### ISSUE TITLE
Feature request: Cookie-based authentication

### ISSUE THREAD

**Issue by vporton** [elastic-coders/pushpull#10]
Please add an option to use a cookie with certain name (such as `sessionid`) for authorization instead of `http-authorization` URL parameter.

This is especially useful with HTTP-only cookies and improves security.

**Comment by vporton** [comment]
Implemented in https://github.com/elastic-coders/pushpull/pull/11 pull request.

**Comment by mpaolini** [comment]
Merged. Thanks @vporton !
